### ISSUE TITLE
file history navigation problems

### ISSUE THREAD

**Issue by zts** [broquaint/Gitalist#10]
When viewing "history" for a file, the first page returned shows only commits touching that file.
However, the next/prev links drop the file parameter, so subsequent pages show the full log.

Additionally, none of the links show the blob at that revision.  It is currently necessary to navigate from the root of the tree after selecting the desired revision.

**Comment by zts** [comment]
In gitweb.cgi, the links on the file history page are "blob", "commitdiff", and "diff to current".
For directory history, the links are "tree" and "commitdiff".

**Comment by zts** [comment]
cce8c9 in my history-fixes branch corrects the action links on the revision list.
The paging links are still broken.

**Comment by zts** [comment]
c0a5486 fixes the paging links.

**Comment by zts** [comment]
Closing as this is now on master.

**Comment by broquaint** [comment]
Closing.
