### ISSUE TITLE
Project (p) parameter is not properly validated.

### ISSUE THREAD

**Issue by zts** [broquaint/Gitalist#12]
1) When requesting an invalid project (eg, /summary?p=DoesNotExist), the response code is 404 but a broken page is still rendered.
2) The p parameter is used unanitised as a relative path, so is vulnerable to directory traversal.

**Comment by zts** [comment]
Fixed in 5232dbdd22d7f2b1ce7d89abd952299a000d94cf

**Comment by broquaint** [comment]
Closing.
