### ISSUE TITLE
Support multiple vhosts (so shadowcat can switch over)

### ISSUE THREAD

**Issue by ranguard** [broquaint/Gitalist#28]

**Comment by broquaint** [comment]
The code [is there](http://git.shadowcat.co.uk/gitweb/gitweb.cgi?p=catagits/Gitalist.git;a=blob;f=lib/Gitalist/Git/CollectionOfRepositories/Vhost.pm;hb=8693e804f274e990ef895f148f8) once we've addressed #27 I reckon this can be wrapped up, as far as the Gitalist code is concerned at least.
