### ISSUE TITLE
Example Apache FastCGI configuration gives a warning

### ISSUE THREAD

**Issue by toupeira** [broquaint/Gitalist#31]
The example configuration specifies the gitalist.fcgi script as DocumentRoot, which causes a warning on Apache restarts because it's not actually a directory. I couldn't find anything in the Apache docs about this use of DocumentRoot, but it seems to work nicely and even gives me pretty URLs without setting up any rewrite rules.

So.. I was wondering if there was a different way to achieve the same behaviour without having the warning message?

**Comment by toupeira** [comment]
I'm also using Apache 2.2.21 and have it setup like in your example, but I still get a warning:

```
$ apache2ctl -t
Warning: DocumentRoot [/usr/lib/cgi-bin/gitalist.fcgi] does not exist
Syntax OK
```

(I'm using the Debian packages for Apache and Gitalist)

**Comment by broquaint** [comment]
I get the same here on Ubuntu, I didn't put the FastCGI docs together so it's not my area of expertise but if I track down a warning-free approach then I'll certainly fix the docs :)

**Comment by halkeye** [comment]
I can post my apache conf. I don't seem to use the same info though.

```
    SetEnv PERL5LIB "/var/www/git/gitalist_deps/lib/perl5"
    SetENV GITALIST_CONFIG "/var/www/git/gitalist.conf" 
    AllowEncodedSlashes On
    DocumentRoot /var/www/git/Gitalist/script
    Alias /static  /var/www/git/Gitalist/root/static
    <Location /static>
      Satisfy Any
      Allow from all
      SetHandler default-handler
    </Location>
    # startup server
    FastCgiServer /var/www/git/Gitalist/script/gitalist_fastcgi.fcgi -processes 3
    # send all urls to this
    Alias / /var/www/git/Gitalist/script/gitalist_fastcgi.fcgi/
```

I have an nginx one too. It doesn't seem exactly the same style as the one in the README, but I can submit a pull request.

**Comment by toupeira** [comment]
@halkeye: thanks, using `Alias / .../gitalist.fcgi/` instead of `DocumentRoot .../gitalist.fcgi` did the trick!

@broquaint: here's a minimal configuration to replace the example in the README:

```
<VirtualHost *:80>
    ServerName gitalist.yourdomain.com
    DocumentRoot /path/to/gitalist/root

    Alias /static /path/to/gitalist/root/static
    <Location /static>
        SetHandler default-handler
    </Location>

    Alias / /path/to/gitalist.fcgi/ # don't forget the trailing slash
    <Files /path/to/gitalist.fcgi>
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch

        # change to fastcgi-script if using mod_fastcgi
        SetHandler fcgid-script
    </Files>

    AllowEncodedSlashes On
</VirtualHost>
```

Note that this will make Gitalist available directly at the root URL, so the sentence following the example ("Now to access your Gitalist instance...") will have to be slightly modified too.
