### ISSUE TITLE
Installation fails if MooseX::Types::ISO8601 >= 0.09

### ISSUE THREAD

**Issue by yibe** [broquaint/Gitalist#35]
When I ran the tests of the latest release, I got a bunch of "cannot coerce non-UTC time" error messages due to [this change of MooseX::Types::ISO8601](https://metacpan.org/diff/release/DLAMBLEY/MooseX-Types-ISO8601-0.08/DLAMBLEY/MooseX-Types-ISO8601-0.09).
For the tests to pass, you can just use `$_[0]->ymd('-') . 'T' . $_[0]->hms(':') . 'Z'` instead of `to_ISO8601DateTimeStr(shift)` in Gitalist::Git::Types. But I'm not sure if it is right to just add a "Z" even for non-UTC datetimes, although it is expected in t/02git_{Repository,object}.t.

**Comment by broquaint** [comment]
I've done basically that in 1369c1484 although I've not looked far and wide to see whether that's the correct approach. But in the absence of failure it will do for now. Thanks for the input, @yibe! Will try to put out a release in the next week or so.
