### ISSUE TITLE
make test 0.004001 on Debian SID - Gitalist::Controller::Fragment::Repository->log "Validation failed

### ISSUE THREAD

**Issue by hggh** [broquaint/Gitalist#52]
I have tested your new version 0.004001 in Debian SID. 

Running make test outputs the following error:

Git version: git version 1.7.10.4
t/00git_version.t ........................................... ok
[error] Caught exception in Gitalist::Controller::Fragment::Repository->log "Validation failed for 'Tuple[Tuple[Object,MooseX::Types::Common::String::NonEmptySimpleStr],Dict[]]' with value "[ [ Gitalist::Git::Repository=HASH(0x7633278), undef ], {  } ], Internal Validation Error is: \n [+] Validation failed for 'Tuple[Object,MooseX::Types::Common::String::NonEmptySimpleStr]' with value "[ Gitalist::Git::Repository{ _util: Gitalist::Git::Util=HASH(0x749bab8), description: "Unnamed repository, edit the .git/description file to set a description", last_change: undef, name: "bare.git", owner: "Jonas Genannt", path: Path::Class::Dir=HASH(0x74758f0) }, undef ]"\n  [+] Must be a non-empty single line of no more than 255 chars" at /usr/share/perl5/MooseX/Method/Signatures/Meta/Method.pm line 435
    MooseX::Method::Signatures::Meta::Method::validate('MooseX::Method::Signatures::Meta::Method=HASH(0x681a010)', 'ARRAY(0x67ebc50)') called at /usr/share/perl5/MooseX/Method/Signatures/Meta/Method.pm line 151
    Gitalist::Git::Repository::get_object('Gitalist::Git::Repository=HASH(0x7633278)', undef) called at /«BUILDDIR»/gitalist-0.004001+dfsg/blib/lib/Gitalist/URIStructure/Repository.pm line 31
    Class::MOP::Class:::before('Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 33
    Class::MOP::Method::Wrapped::__ANON__('Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 91
    Gitalist::Controller::Fragment::Repository::log('Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x69ec940)', 'Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst.pm line 1668
    eval {...} called at /usr/share/perl5/Catalyst.pm line 1668
    Catalyst::execute('Gitalist=HASH(0x77366d0)', 'Gitalist::Controller::Fragment::Repository', 'Catalyst::Action=HASH(0x69ec940)') called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('Gitalist=HASH(0x77366d0)', 'Gitalist::Controller::Fragment::Repository', 'Catalyst::Action=HASH(0x69ec940)') called at /usr/share/perl5/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x69ec940)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/ActionChain.pm line 36
    Catalyst::ActionChain::dispatch('Catalyst::ActionChain=HASH(0x74da678)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Controller.pm line 158
    Catalyst::Controller::_ACTION('Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x69ebca0)', 'Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst.pm line 1668
    eval {...} called at /usr/share/perl5/Catalyst.pm line 1668
    Catalyst::execute('Gitalist=HASH(0x77366d0)', 'Gitalist::Controller::Fragment::Repository', 'Catalyst::Action=HASH(0x69ebca0)') called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('Gitalist=HASH(0x77366d0)', 'Gitalist::Controller::Fragment::Repository', 'Catalyst::Action=HASH(0x69ebca0)') called at /usr/share/perl5/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x69ebca0)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'forward', 'Gitalist=HASH(0x77366d0)', '_ACTION') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'Gitalist=HASH(0x77366d0)', '_ACTION') called at /usr/share/perl5/Catalyst.pm line 358
    Catalyst::forward('Gitalist=HASH(0x77366d0)', '_ACTION') called at /usr/share/perl5/Catalyst/Controller.pm line 132
    Catalyst::Controller::_DISPATCH('Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x692a358)', 'Gitalist::Controller::Fragment::Repository=HASH(0x60d2d58)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst.pm line 1668
    eval {...} called at /usr/share/perl5/Catalyst.pm line 1668
    Catalyst::execute('Gitalist=HASH(0x77366d0)', 'Gitalist::Controller::Fragment::Repository', 'Catalyst::Action=HASH(0x692a358)') called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('Gitalist=HASH(0x77366d0)', 'Gitalist::Controller::Fragment::Repository', 'Catalyst::Action=HASH(0x692a358)') called at /usr/share/perl5/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x692a358)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'forward', 'Gitalist=HASH(0x77366d0)', '/fragment/repository/_DISPATCH') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'Gitalist=HASH(0x77366d0)', '/fragment/repository/_DISPATCH') called at /usr/share/perl5/Catalyst.pm line 358
    Catalyst::forward('Gitalist=HASH(0x77366d0)', '/fragment/repository/_DISPATCH') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 105
    Catalyst::Dispatcher::dispatch('Catalyst::Dispatcher=HASH(0x50bd190)', 'Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst.pm line 1614
    Catalyst::dispatch('Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Plugin/Static/Simple.pm line 77
    Class::MOP::Class:::around('CODE(0x50e9ef0)', 'Gitalist=HASH(0x77366d0)') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 162
    Class::MOP::Method::Wrapped::__ANON__('Gitalist=HASH(0x77366d0)') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 91
    Gitalist::dispatch('Gitalist=HASH(0x77366d0)') called at /usr/share/perl5/Catalyst/Plugin/SubRequest.pm line 101
    Catalyst::Plugin::SubRequest::sub_request_response('Gitalist=HASH(0x74e4b40)', '/fragment/bare.git/shortlog', 'HASH(0x774b308)', 'HASH(0x77220f8)') called at /usr/share/perl5/Catalyst/Plugin/SubRequest.pm line 81
    Catalyst::Plugin::SubRequest::sub_request('Gitalist=HASH(0x74e4b40)', '/fragment/bare.git/shortlog', 'HASH(0x774b308)', 'HASH(0x77220f8)') called at /usr/share/perl5/Catalyst/View/Component/SubInclude/SubRequest.pm line 93
    Catalyst::View::Component::SubInclude::SubRequest::generate_subinclude('Catalyst::View::Component::SubInclude::SubRequest=HASH(0x6091...', 'Gitalist=HASH(0x74e4b40)', '/fragment/repository/shortlog', 'ARRAY(0x7757018)') called at /usr/share/perl5/Catalyst/View/Component/SubInclude.pm line 155
    Catalyst::View::Component::SubInclude::_subinclude_using('Gitalist::View::Default=HASH(0x6058620)', 'Gitalist=HASH(0x74e4b40)', 'Catalyst::View::Component::SubInclude::SubRequest', '/fragment/repository/shortlog', 'ARRAY(0x7757018)') called at /usr/share/perl5/Catalyst/View/Component/SubInclude.pm line 149
    Catalyst::View::Component::SubInclude::_subinclude('Gitalist::View::Default=HASH(0x6058620)', 'Gitalist=HASH(0x74e4b40)', '/fragment/repository/shortlog', 'ARRAY(0x7757018)') called at /usr/share/perl5/Catalyst/View/Component/SubInclude.pm line 136
    Catalyst::View::Component::SubInclude::__ANON__('Gitalist=HASH(0x74e4b40)', '/fragment/repository/shortlog', 'ARRAY(0x7757018)') called at /usr/share/perl5/Catalyst/Component/ContextClosure.pm line 10
    Catalyst::Component::ContextClosure::**ANON**('/fragment/repository/shortlog', 'ARRAY(0x7757018)') called at /«BUILDDIR»/gitalist-0.004001+dfsg/root/repository/summary.tt2 line 6
    eval {...} called at /«BUILDDIR»/gitalist-0.004001+dfsg/root/repository/summary.tt2 line 6
    eval {...} called at /«BUILDDIR»/gitalist-0.004001+dfsg/root/repository/summary.tt2 line 7
    Template::Document::**ANON**('Template::Context=HASH(0x605b9f0)') called at /usr/lib/perl5/Template/Document.pm line 163
    eval {...} called at /usr/lib/perl5/Template/Document.pm line 161
    Template::Document::process('Template::Document=HASH(0x7496b98)', 'Template::Context=HASH(0x605b9f0)') called at /usr/lib/perl5/Template/Context.pm line 347
    eval {...} called at /usr/lib/perl5/Template/Context.pm line 321
    Template::Context::process('Template::Context=HASH(0x605b9f0)', 'Template::Document=HASH(0x7496b98)') called at /usr/lib/perl5/Template/Service.pm line 94
    eval {...} called at /usr/lib/perl5/Template/Service.pm line 91
    Template::Service::process('Template::Service=HASH(0x6058f50)', 'repository/summary.tt2', 'HASH(0x7722398)') called at /usr/lib/perl5/Template.pm line 66
    Template::process('Template=HASH(0x6058860)', 'repository/summary.tt2', 'HASH(0x7722398)', 'SCALAR(0x5a15528)') called at /usr/share/perl5/Catalyst/View/TT.pm line 263
    Catalyst::View::TT::render('Gitalist::View::Default=HASH(0x6058620)', 'Gitalist=HASH(0x74e4b40)', 'repository/summary.tt2') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 50
    Class::MOP::Method::Wrapped::**ANON**('Gitalist::View::Default=HASH(0x6058620)', 'Gitalist=HASH(0x74e4b40)', 'repository/summary.tt2') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 91
    Gitalist::View::Default::render('Gitalist::View::Default=HASH(0x6058620)', 'Gitalist=HASH(0x74e4b40)', 'repository/summary.tt2') called at /usr/share/perl5/Catalyst/View/TT.pm line 223
    eval {...} called at /usr/share/perl5/Catalyst/View/TT.pm line 223
    Catalyst::View::TT::process('Gitalist::View::Default=HASH(0x6058620)', 'Gitalist=HASH(0x74e4b40)', 'rest') called at /usr/share/perl5/Catalyst/Action/Serialize/View.pm line 29
    Catalyst::Action::Serialize::View::execute('Catalyst::Action::Serialize::View=HASH(0x749b5d8)', 'Gitalist::Controller::Root=HASH(0x60a5e00)', 'Gitalist=HASH(0x74e4b40)', 'Default') called at /usr/share/perl5/Catalyst/Action/Serialize.pm line 50
    eval {...} called at /usr/share/perl5/Catalyst/Action/Serialize.pm line 49
    Catalyst::Action::Serialize::execute('Catalyst::Action::Serialize=HASH(0x6a27b50)', 'Gitalist::Controller::Root=HASH(0x60a5e00)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst.pm line 1668
    eval {...} called at /usr/share/perl5/Catalyst.pm line 1668
    Catalyst::execute('Gitalist=HASH(0x74e4b40)', 'Gitalist::Controller::Root', 'Catalyst::Action::Serialize=HASH(0x6a27b50)') called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('Gitalist=HASH(0x74e4b40)', 'Gitalist::Controller::Root', 'Catalyst::Action::Serialize=HASH(0x6a27b50)') called at /usr/share/perl5/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action::Serialize=HASH(0x6a27b50)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst/Controller.pm line 171
    Catalyst::Controller::_END('Gitalist::Controller::Repository=HASH(0x60a9c58)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x694edd0)', 'Gitalist::Controller::Repository=HASH(0x60a9c58)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst.pm line 1668
    eval {...} called at /usr/share/perl5/Catalyst.pm line 1668
    Catalyst::execute('Gitalist=HASH(0x74e4b40)', 'Gitalist::Controller::Repository', 'Catalyst::Action=HASH(0x694edd0)') called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('Gitalist=HASH(0x74e4b40)', 'Gitalist::Controller::Repository', 'Catalyst::Action=HASH(0x694edd0)') called at /usr/share/perl5/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x694edd0)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'forward', 'Gitalist=HASH(0x74e4b40)', '_END') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'Gitalist=HASH(0x74e4b40)', '_END') called at /usr/share/perl5/Catalyst.pm line 358
    Catalyst::forward('Gitalist=HASH(0x74e4b40)', '_END') called at /usr/share/perl5/Catalyst/Controller.pm line 135
    Catalyst::Controller::_DISPATCH('Gitalist::Controller::Repository=HASH(0x60a9c58)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst/Action.pm line 65
    Catalyst::Action::execute('Catalyst::Action=HASH(0x692ae98)', 'Gitalist::Controller::Repository=HASH(0x60a9c58)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst.pm line 1668
    eval {...} called at /usr/share/perl5/Catalyst.pm line 1668
    Catalyst::execute('Gitalist=HASH(0x74e4b40)', 'Gitalist::Controller::Repository', 'Catalyst::Action=HASH(0x692ae98)') called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 22
    Catalyst::Plugin::StackTrace::execute('Gitalist=HASH(0x74e4b40)', 'Gitalist::Controller::Repository', 'Catalyst::Action=HASH(0x692ae98)') called at /usr/share/perl5/Catalyst/Action.pm line 60
    Catalyst::Action::dispatch('Catalyst::Action=HASH(0x692ae98)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 257
    Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'forward', 'Gitalist=HASH(0x74e4b40)', '/repository/_DISPATCH') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 237
    Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x50bd190)', 'Gitalist=HASH(0x74e4b40)', '/repository/_DISPATCH') called at /usr/share/perl5/Catalyst.pm line 358
    Catalyst::forward('Gitalist=HASH(0x74e4b40)', '/repository/_DISPATCH') called at /usr/share/perl5/Catalyst/Dispatcher.pm line 105
    Catalyst::Dispatcher::dispatch('Catalyst::Dispatcher=HASH(0x50bd190)', 'Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst.pm line 1614
    Catalyst::dispatch('Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst/Plugin/Static/Simple.pm line 77
    Class::MOP::Class:::around('CODE(0x50e9ef0)', 'Gitalist=HASH(0x74e4b40)') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 162
    Class::MOP::Method::Wrapped::__ANON__('Gitalist=HASH(0x74e4b40)') called at /usr/lib/perl5/Class/MOP/Method/Wrapped.pm line 91
    Gitalist::dispatch('Gitalist=HASH(0x74e4b40)') called at /usr/share/perl5/Catalyst.pm line 1964
    Catalyst::**ANON**() called at /usr/share/perl5/Try/Tiny.pm line 76
    eval {...} called at /usr/share/perl5/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x74dfc40)', 'Try::Tiny::Catch=REF(0x74e43a8)') called at /usr/share/perl5/Catalyst.pm line 1970
    Catalyst::handle_request('Gitalist', 'env', 'HASH(0x7530098)', 'response_cb', 'CODE(0x74b1558)') called at /usr/share/perl5/Catalyst/Engine.pm line 685
    Catalyst::Engine::**ANON**('CODE(0x74b1558)') called at /usr/share/perl5/HTTP/Message/PSGI.pm line 98
    HTTP::Message::PSGI::res_from_psgi('CODE(0x74b1498)') called at /usr/share/perl5/HTTP/Message/PSGI.pm line 153
    HTTP::Response::from_psgi('HTTP::Response', 'CODE(0x74b1498)') called at /usr/share/perl5/Plack/Test/MockHTTP.pm line 24
    Plack::Test::MockHTTP::**ANON**() called at /usr/share/perl5/Try/Tiny.pm line 71
    eval {...} called at /usr/share/perl5/Try/Tiny.pm line 67
    Try::Tiny::try('CODE(0x73ae0d0)', 'Try::Tiny::Catch=REF(0x777ef10)') called at /usr/share/perl5/Plack/Test/MockHTTP.pm line 27
    Plack::Test::MockHTTP::**ANON**('HTTP::Request=HASH(0x74b1ae0)') called at /usr/share/perl5/Catalyst/Test.pm line 280
    Catalyst::Test::**ANON**('CODE(0x73adec0)') called at /usr/share/perl5/Plack/Test/MockHTTP.pm line 33
    Plack::Test::MockHTTP::test_psgi('app', 'CODE(0x7381958)', 'mangle_response', 'CODE(0x2963588)', 'app', 'CODE(0x73ae3d0)', 'client', 'CODE(0x73ae370)') called at /usr/share/perl5/Plack/Test.pm line 17
    Plack::Test::test_psgi('app', 'CODE(0x7381958)', 'mangle_response', 'CODE(0x2963588)', 'app', 'CODE(0x73ae3d0)', 'client', 'CODE(0x73ae370)') called at /usr/share/perl5/Catalyst/Test.pm line 283
    Catalyst::Test::_request('HASH(0x1775cb0)', '/bare.git') called at /usr/share/perl5/Catalyst/Test.pm line 324
    Catalyst::Test::_local_request('Gitalist', '/bare.git') called at /usr/share/perl5/Catalyst/Test.pm line 31
    Catalyst::Test::__ANON__('/bare.git') called at t/01app.t line 18"

**Comment by broquaint** [comment]
This is due to the test bare.git repository no longer being considered a valid git repo in recent versions of git.

However it is not a test failure, just an annoyingly loud error message. If the error is causing build issues however let me know and I'll look into it further.

**Comment by hggh** [comment]
This does not cause an build error, but it's not very nice. I have looked deeper into it. 

First you need to recreate the bare repro with a current version of git, and than add one commit (git --allow-empty -m "foo").

That will fix the build error.

It would be nice if you can add this to the next version

**Comment by broquaint** [comment]
Fixed in af2c5a6, will try to push out a new release soon.

**Comment by broquaint** [comment]
That fix is now in 0.004002.

**Comment by hggh** [comment]
:+1: :)
