### ISSUE TITLE
Can't load tag tree view

### ISSUE THREAD

**Issue by doherty** [broquaint/Gitalist#53]
```
[error] Caught exception in Gitalist::Controller::Fragment::Ref->tree "Can't locate object method "tree" via package "Gitalist::Git::Object::Tag" at lib/Gitalist/Controller/Fragment/Ref.pm line 51."
```

when I try to load something like `/perl/v5.16.3-RC1/tree`

**Comment by broquaint** [comment]
Thanks for that, looks like we didn't implement a bunch of methods for Tag objects! Will look to correct that as soon as I can.

**Comment by broquaint** [comment]
That commit fixes the issue which was basically that the way we represented tags was too simplistic. Thanks again for the heads up, @doherty!
